### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by rain-sumire** [GIFUniversity/About#8]
Dear whom may concern,  
Hello. I want to get everything for free!

Regards,  
rain-sumire

**Comment by Cubik65536** [comment]
Hi,
🎉 Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
Cubik65536
President, Get It Free University

------

您好！
🎉 恭喜您！您的申请被通过了而且您的Offer已经通过邮件发送给您，请在 7 天内同意邀请。

此致
Cubik65536
白嫖怪大学校长
